### ISSUE TITLE
業務フロー（またはシステムフロー）があれば共有して欲しい

### ISSUE THREAD

**Issue by y-tsuchie** [YataFumika/sunday_play#8]
- 何かツールとかサービスを使って業務の全体の流れを把握したい
  - 何を作らないといけないかが現状わからない土江

例の場所では、 https://cacoo.com/ja/
とか使ってるけど、有料なのでなやみどころ

**Comment by YataFumika** [comment]
最低限のマイルストーンとしては、予約できればいいんじゃないかと思いました。

## 運用フロー

### 登録

**部屋と時間が決まってる利用者**

1. ユーザは、トップページを開く
2. ユーザは、予約したい部屋と時間を決め、該当時間に対して「予約」ボタンをクリックする
3. システムは、予約画面を開く
4. ユーザは、連絡先等の情報を入力する
5. ユーザは、「確定」ボタンをクリックする
6. システムは、予約を保存する
7. システムは、トップページへ遷移し、登録した予約情報を表示する

**部屋と時間がふわっとしてる利用者**

1. ユーザは、トップページを開く
2. ユーザは、自分が使いたい目的や部屋の広さ、空き時間などから、予約したい部屋と時間を検索する
3. システムは、検索条件に該当する部屋を画面に表示する
4. ユーザは、良さそうな部屋に対して「予約」ボタンをクリックする
5. 「部屋と時間が決まってる利用者」の3以降と同じ


※仮登録機能が必要かどうかは後々検討する

### 照会

1. ユーザは、トップページを開く
2. ユーザは、自分が予約した部屋、時間から検索する
3. システムは、検索条件に合致する部屋を表示する
4. ユーザは、自分の予約を確認する

### 変更

1. 「照会」の1~3と同様
2. ユーザは、「編集」ボタンをクリックする
3. システムは、予約編集画面を開く
4. ユーザは、変更内容を入力する
5. ユーザは、「確定」ボタンをクリックする
6. システムは、予約を保存する
7. システムは、予約詳細画面へ遷移し、保存した内容を表示する

### 削除

1. 「照会」の1~3と同様
2. ユーザは、「削除」ボタンをクリックする
3. システムは、該当の予約を削除する
4. システムは、トップページへ遷移する

**Comment by YataFumika** [comment]
@y-tsuchie ざっくりですが、wikiに記載しました。
足りない部分があれば足しますので、ご確認ください。
